steps:
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  - name: hashicorp/terraform:1.5.0
    id: Import Existing Service
    entrypoint: sh
    args:
      - -c
      - |
        if terraform state list 2>/dev/null | grep -q "google_cloud_run_service.service"; then
          echo "Service already imported"
        else
          terraform import \
            -input=false \
            -var-file="environments/${_ENV}.tfvars" \
            google_cloud_run_service.service \
            "locations/${_REGION}/namespaces/${_PROJECT_ID}/services/${_SERVICE_NAME}" ||
            echo "Import may have failed but continuing"
        fi

  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -input=false \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="service_name=${_SERVICE_NAME}" \
          -var-file="environments/${_ENV}.tfvars" \
          -out=tfplan

  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -input=false -auto-approve tfplan
        terraform output

substitutions:
  _ENV: dev
  _PROJECT_ID: eastern-augury-477909-q6
  _REGION: us-central1
  _SERVICE_NAME: frontend-web

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s

