steps:
  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - terraform init -input=false

  # Step 2: Terraform Plan
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -input=false \
          -var-file=environments/${_ENV}.tfvars \
          -out=tfplan

  # Step 3: Terraform Apply
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -input=false -auto-approve tfplan

substitutions:
  _ENV: dev

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 600s


