steps:
  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  # Step 2: Import existing service (only once)
  - name: hashicorp/terraform:1.5.0
    id: Import Existing Service
    entrypoint: sh
    args:
      - -c
      - |
        echo "🔍 Checking if service already imported..."
        if terraform state list 2>/dev/null | grep -q "google_cloud_run_service.service"; then
          echo "✅ Already imported. Skipping."
        else
          echo "📥 Importing service..."
          terraform import \
            -input=false \
            -var="project_id=${_PROJECT_ID}" \
            -var="region=${_REGION}" \
            -var="service_name=${_SERVICE_NAME}" \
            -var-file="environments/${_ENV}.tfvars" \
            google_cloud_run_service.service \
            "locations/${_REGION}/namespaces/${_PROJECT_ID}/services/${_SERVICE_NAME}" \
            || echo "⚠️ Import failed, but continuing"
        fi

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        echo "📋 Running Terraform plan..."
        terraform plan \
          -input=false \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="service_name=${_SERVICE_NAME}" \
          -var-file="environments/${_ENV}.tfvars" \
          -out=tfplan

  # Step 4: Terraform Apply
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        echo "🚀 Applying Terraform changes..."
        terraform apply -input=false -auto-approve tfplan
        echo "📊 Outputs:"
        terraform output

substitutions:
  _ENV: prod
  _PROJECT_ID: eastern-augury-477909-q6
  _REGION: us-central1
  _SERVICE_NAME: frontend-web

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s


