steps:
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform init

  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform plan \
          -var-file="environments/${_ENV}.tfvars"

  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform apply \
          -auto-approve \
          -var-file="environments/${_ENV}.tfvars"

substitutions:
  _ENV: "dev"

options:
  logging: CLOUD_LOGGING_ONLY
