steps:
  # Step 1: Terraform Init
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Init'
    dir: 'scaling'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # Step 2: Terraform Plan (for visibility in logs)
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Plan'
    dir: 'scaling'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Planning scaling changes for ${_ENV} environment..."
        terraform plan -var-file=environments/${_ENV}-scaling.tfvars

  # Step 3: Terraform Apply (update scaling)
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Apply'
    dir: 'scaling'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Applying scaling changes for ${_ENV} environment..."
        terraform apply -auto-approve -var-file=environments/${_ENV}-scaling.tfvars
        echo "✅ Scaling configuration updated successfully!"

substitutions:
  _ENV: 'dev'  # default environment, can be overridden in the trigger

options:
  logging: CLOUD_LOGGING_ONLY
